name: The future of culture
favicon: null
layout_spectrum: 0.8793880259618163
typography_spectrum: 0.983125046826899
title: The future of culture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8660018285736442
  lightness: 0.643049007980153
  saturation: 0.4362584229093045
  rhythmicContrast: 0.7532353652641177
purpose: []
